### ISSUE TITLE
Update user properties

### ISSUE THREAD

**Issue by fabianmarz** [themosis/documentation#10]
Regarding to the official [Wordpress reference](http://codex.wordpress.org/Function_Reference/wp_update_user) there are no fields called "email" or "url" which are mentioned in the [Themosis User Docs](http://framework.themosis.com/docs/user/).

**Comment by jlambe** [comment]
Thanks for catching this one. It is indeed `user_email` and `user_url`. Will update this as soon as possible.

**Comment by fabianmarz** [comment]
I have done this for you :)
