### ISSUE TITLE
Confused with the views share

### ISSUE THREAD

**Issue by rovillesarate** [themosis/documentation#12]
Hi! I am a bit confused with the views share.

Where do i place this? in the routes? inside a route?

Can you give an example of how to use it in a route? and where to place it?

**Comment by jlambe** [comment]
Hi,

you can call the `View::share` inside routes.php, inside controllers or inside any files located inside the `admin` directory.

With this method, you'll share a piece of data for all your views, so you want to place it somewhere before any view is called.
