### ISSUE TITLE
Roadmap for documentation to do

### ISSUE THREAD

**Issue by dstollie** [themosis/documentation#17]
I see you've added alot of new stuff in the dev-master especially the Helper class has been growed significantly. If you would like some help with documenting stuff Im willing to help you. If you are looking for some help, it would be easier for others if you could setup some list with "stuff to document'.

**Comment by jlambe** [comment]
Hi @dstollie,

thanks for your help. I'm currently finishing the docs for next release. Once release 1.2.0 is out, I will start a revamped of the documentation website and probably add a way to communicate roadmap, tips and list of stuff to help evolve the project.

If you want to document the Helper functions, you can still grab a copy of this repo, open the `helpers.md` file in a markdown editor and add forgotten functions. You should find a description of each function into the code to help you. Submit your pull request, I will merge it and review it before release. Thanks for kind words and your support!

**Comment by Givx** [comment]
Sorry for my english, but the section about the plugin is not realy easy for start the developpement. How use the mvc structure for view in backend of Wordpress ? I know realy good pratice of laravel, but it's not realy clair here.

**Comment by jlambe** [comment]
@Givx One thing to keep in mind is that you're still doing WordPress development. So for example, the Routing is only functional on the "front-end" part of WordPress. If you're trying to use the Route class for building custom admin pages inside the WordPress Administration, you're going for troubles :)

You can define front-end routes from a plugin. The idea here is that your plugin can provide routes and views a theme have not yet integrated. Then if from the theme you want to alter or overwrite a plugin route and its view, then you can.

I would suggest that you open a new issue and perhaps give us some hints on what you're trying to do within the WordPress Administration and then I'll be able to give you some help.

I'm going to close this issue as it's not relevant to original post.
