### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ramon-villain** [themosis/documentation#20]
Hi @jlambe I'm ready to translate the documentation into my native language (pt-br), how do you think we could proceed? Something outside Themosis' website, some language selector there or just a branch in this repo? The community is getting bigger everyday, as well as the brazilian devs.

**Comment by jlambe** [comment]
Hi @ramon-villain,
that's great news!

I have planned to develop a new website for the documentation. I suppose at the end, the pt-br version should be available on the website.

You can start a fork of this repository and write the pt-br documentation. I'll take a look on how to give you access to this repository and we'll merge your documentation over here so everything is centralized. On my side, I have requests for a french documentation as well.

Would you like to also participate in the development of the new website?

**Comment by dstollie** [comment]
@jlambe if you need some help with the development of the new website, Im willing to help you where possible, so give me a shout!

**Comment by ramon-villain** [comment]
@jlambe ohhh it's f*cking awesome man, and I'll fork the repo and start the translation part. :)

And about the new website, I'm very thankful for you offering me a role in this new step. I'm in :+1: 🤘🏼

**Comment by jlambe** [comment]
@ramon-villain and @dstollie , can you send me an email to contact@themosis.com so I get your personal adresses. I'm glad to include you in the process of the website but I don't want more people to be involved right now as it will be hard to manage. I will write you personally and continue the discussion out of github.
