### ISSUE TITLE
Helpers page: themosis_set_path is actually themosis_set_paths

### ISSUE THREAD

**Issue by mengidd** [themosis/documentation#22]
A small typo in the Helpers page: https://github.com/themosis/documentation/blob/master/helpers.md#themosis_set_patharray-paths

themosis_set_path is supposed to be themosis_set_paths.

**Comment by jlambe** [comment]
Indeed, nice catch! Can you provide a pull request for the changes?

**Comment by jlambe** [comment]
The function helper is no longer available inside the framework.
