### ISSUE TITLE
PHP 5.5 requirement

### ISSUE THREAD

**Issue by williamrijksen** [themosis/documentation#28]
Hello,

The documentation says the minimal requirement for PHP = 5.4 (http://framework.themosis.com/docs/installation/), but the `composer.json` is set to `>= 5.5.9`.

What is the right value? @jlambe.

Reference: https://github.com/themosis/framework/commit/66c1a67db2694b6eb47f801170f625563dd69ee7.

**Comment by jlambe** [comment]
Hello,
the stable version needs PHP 5.4 minimum.

The current dev branch, I changed to 5.5.9 for a test but it's wrong and needs to be updated. If you want to test the current dev branch, you need PHP 5.6 minimum.

**Comment by williamrijksen** [comment]
@jlambe Okay thanks! In that case i can use Themosis with 5.4.

PS thank you all for this amazing framework. It helps me a lot to structure my application!

**Comment by jlambe** [comment]
👍
