### ISSUE TITLE
Configuration Mistake

### ISSUE THREAD

**Issue by unstoppablecarl** [themosis/documentation#34]
The configuration page has the following: 

> Let's grab all properties of the theme's `theme.config.php` file:
> ```php
> $all = Config::get('application');
> ```

Based on the explanation that comes after (the above code producing an exception in a fresh install) I believe it should be:
```php
$all = Config::get('theme');
```

**Comment by jlambe** [comment]
In version 1.3 ? If yes, it's indeed a mistake and your assumption is correct ;)
