### ISSUE TITLE
Metabox mapping documentation

### ISSUE THREAD

**Issue by jlambe** [themosis/documentation#45]
Provide metabox mapping documentation...

**Comment by LittleHamster** [comment]
Hello Julien, 
is this issue the same as the Meta Guide link in meta box page?
this link does not work: 
http://framework.themosis.com/docs/1.3/metabox/%7B%7Bmeta%7D%7D/meta

used in here: http://framework.themosis.com/docs/1.3/metabox/#retrieve-data

**Comment by jlambe** [comment]
@LittleHamster No, it isn't but thanks for pointing the broken link.

There is a `map()` method available to automatically store a custom field value to a `WP_Post` property on save.
