### ISSUE TITLE
PLugin define key in supports.config.php theme

### ISSUE THREAD

**Issue by Givx** [themosis/documentation#47]
I don't know for not display this message : 

Your application do not handle the following plugin:

Inside the file, "Define your plugin theme support key. Once defined, make sure to add the key into your theme `supports.config.php` in order to remove this admin notice"

In the documentation is not really clear

**Comment by jlambe** [comment]
Inside the plugin, you had to define a plugin key inside the `$vars` array. From your theme, in the `supports.config.php`, add your plugin key to the array in order to tell that your theme is supporting your custom plugin.

**Comment by Givx** [comment]
i already doing that, but the message not disapear

**Comment by jlambe** [comment]
Can you post your plugin main file and supports config one?

**Comment by Givx** [comment]
ok i understand if the active theme is not a themosis theme you have this message. 
Sorry.

**Comment by jlambe** [comment]
Or if your theme is a "classic" theme, just call the `add_theme_supports('plugin-key');`
