### ISSUE TITLE
Ajax::listen not working for me

### ISSUE THREAD

**Issue by bumbella** [themosis/documentation#48]
Please help me. I can't make ajax form with Themosis framework. admin-ajax php 200 OK
What is the problem? I make anything wrong?
Thanx for you.

resources/admin/ajax.php
Ajax::run('send_contact_mail', 'both', function(){
    echo 'assad';
    die();
});

javascript file:
$.ajax({
    url: themosis.ajaxurl,
    type: 'POST',
    dataType: 'json',
        data: {
            action: 'send_contact_mail',
        }
    })
.done(function(data) {
    console.log(data);
});

**Comment by jlambe** [comment]
Since release 1.3, the method used is `Ajax::listen()`. Based on the documentation, your parameters are wrong. You need to switch second and third parameters. Your callback is the second one now and you can omit the `both` value as it is the default:

```php
Ajax::listen('send_contact_mail', function () {
    echo 'assad';
    die();
});
```
