### ISSUE TITLE
Cant' load View from a plugin controller

### ISSUE THREAD

**Issue by AMarwen** [themosis/documentation#54]
I can't load the View file from inside the controller method, I have tried this 2 solution and none of them works (I always get a message saying that the view is  not found) : 

1. return view('/newsLetter.twig');
2. return view(themosis_path('plugin.com.plugin.newsletter.resources').'views/newsLetter.twig');

note : the plugin works correctly if I echo the message directly from inside my controller and themosis_path('plugin.com.plugin.newsletter.resources') return a correct path to the plugin resources folder.

**Comment by jlambe** [comment]
It should be `view(newsLetter.twig);` without any slashes. It's not a "classic" path to give but a `dot` notation path.
