### ISSUE TITLE
Compile Views in Storage

### ISSUE THREAD

**Issue by dieg0** [themosis/documentation#55]
I have a local version, that has its own compiled view such as:
```
/storage/views/c5060c6bbe13e3122cb409950a4ba0cdcc9a0f57.php
/storage/views/fff12666fb99ee057204a844e9ac50b527325a15.php
```

But when I load the repository in the server, files inside /storage/views/ are omitted.
I've seen this is an issue that is being addressed on future relases. So I copied the compiled views from my local repo into the server. But then I realized on the server's log, themosis is looking for a different compiled file of the views:

```
PHP Warning:  include(): Failed opening '/storage/views//84d3c649c9572fb2fa35f17823df232ec7101557.php'
```

This means the hash generated is different on the server than on my local version. I do not care to mantain the hash from local to the server. But I would like for themosis to recompile the views. Is there a command to recompile the views?

**Comment by jlambe** [comment]
You don't have to push your compiled views to the server. Just make sure that a `storage/views` folder exists on your server and freshly compiled views will go there. No need to push the local ones.

**Comment by dieg0** [comment]
Right, I had to modify storage folder permission like this

`sudo chmod -R 777 storage`
