### ISSUE TITLE
Plugin Documentation Access

### ISSUE THREAD

**Issue by Neidra** [themosis/documentation#60]
Hey Themosis Team,
Don't know where I have to post this, but i can't access to the "Plugin" documentation ([link](https://framework.themosis.com/docs/1.3/plugin)) the following message is displayed

> Error establishing a database connection

Same message for the pages "wp-cli", "Multisite" and "Theme"

**Comment by jlambe** [comment]
@Neidra Sorry for the inconvenience, the documentation website is back online now. We've upgrade our server configuration to PHP7.2.
