### ISSUE TITLE
Update Taxonomy Documentation to Reflect Changes from 2.0

### ISSUE THREAD

**Issue by Kylechalm** [themosis/documentation#64]
Hey, I have been using the Beta2 release of 2.0 and have been loving the changes so far. 

However: it appears that the Taxonomy documentation has not been updated yet, while the interface for (at least) adding custom fields has clearly changed (with the removal of the `addFields` method and inclusion of the `TaxField` class). 

It would be great to get clear documentation on this as the examples currently available are broken.

Thanks and keep up the great work!

**Comment by Tronix117** [comment]
Yes, same request around here, sounds like there has been a lot of changes, and no docs to use them...

**Comment by jlambe** [comment]
@Kylechalm Hi sorry for the delay, I personnaly missed this one. I'll try to update the docs regarding Taxonomy as soon as possible. In the meantime, here is a code snippet with available methods:

```php
Taxonomy::make('taxonomy_slug, $post-type, 'Plural Names', 'Singular Name')
    ->set();
```

To customize the labels, call the `setLabels()` method. To pass custom arguments/properties like in the register taxonomy function, use the `setArguments()` method. Call these methods before the `set()` one.

Unfortunately,  the taxonomy class no longer offers terms custom fields. The feature has not yet been implemented on 2.0.

**Comment by twosg** [comment]
I also would like to see the forms page (https://framework.themosis.com/docs/2.0/form/) completed, as for a Laravel newbie its hard to find out how that is intended to work :)

I've got my form and want to handle it now, like display the errors or save the form data.

Seems `$form->handleRequest($this->request);` does not make that alone

I also can donate something if you tell me where.

**Comment by jlambe** [comment]
The Themosis framework 2.0 has been officially released with updated documentation on form and taxonomy.
https://framework.themosis.com/
