### ISSUE TITLE
incorrect path on Extending Twig

### ISSUE THREAD

**Issue by nathanopereira** [themosis/documentation#74]
Hello, 

The path for `Facades\Twig` in example from [Extending Twig](https://framework.themosis.com/docs/2.0/twig/#extending-twig) is incorrect;

### Incorrect (Facade)
```php
use Themosis\Support\Facade\Twig;
```
### Correct (Facades)
```php
use Themosis\Support\Facades\Twig;
```
I hope to be helping

**Comment by jlambe** [comment]
@nathanopereira Thanks for catching this one. Would you like to submit a PR against the `2.0` branch ?

**Comment by nathanopereira** [comment]
Ok, PR opened #75
